# Define global CODEOWNERS
global:
  "*.js": js-team@example.com
  "*.py": python-team@example.com

# Define CODEOWNERS by repository topic
topics:
  frontend:
    "*.css": frontend-team@example.com
    "*.html": frontend-team@example.com
    "*.abcf": abcd-team@example.com
  backend:
    "*.go": backend-team@example.com
    "*.java": backend-team@example.com
    "*.abcb": backend-team@example.com

# Define CODEOWNERS for specific repositories
repositories:
  "org/repo1":
    "/docs/": documentation-team@example.com
  "org/repo2":
    "/src/": core-team@example.com
