name: Sync CODEOWNERS File

on:
  repository_dispatch:
    types: [sync_codeowners]

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-codeowners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install @octokit/rest js-yaml

      - name: Sync CODEOWNERS file and create PR
        run: node sync_codeowners/sync_codeowners.js
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          TARGET_REPO_OWNER: ${{ github.event.client_payload.owner }}
          TARGET_REPO_NAME: ${{ github.event.client_payload.repo }}
